name: Run Tests on BrowserStack

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      runmode:
        description: 'Run mode (e.g., BROWSERSTACK, LOCAL)'
        required: true
        default: 'BROWSERSTACK'
      platform:
        description: 'Platform (e.g., ANDROID, IOS)'
        required: true
        default: 'ANDROID'

jobs:
  browserstack-tests:
    runs-on: ubuntu-latest
    environment: BROWSER_STACK

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK (Java 11 in this example)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies
      - name: Install Maven Dependencies
        run: mvn install -DskipTests

      # Run Maven Tests with BrowserStack
      - name: Run Tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.USER_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: mvn test -Drunmode=${{ inputs.runmode }} -Dplatform=${{ inputs.platform }}
